//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPortal.Web.locations.y_swim_center
{


    public partial class y_swim_center_in_dundalk
    {
    }
}
