//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPortal.Web.locations.family_center_ys
{


    public partial class y_swim_center_in_dundalk_baltimore_county
    {
    }
}
