//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPortal.Web {
    
    
    public partial class Y_Bio {
        
        /// <summary>
        /// YDCarouselInfoV21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDCarouselInfoV2 YDCarouselInfoV21;
        
        /// <summary>
        /// bioTab1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.Controls.YDTabControl bioTab1;
    }
}
