//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//		Template updated by: Mohammad Ashraful Alam, Microsoft MVP, ASP.NET [admin@ashraful.net]
//		Modification comment: made few items mockable. (03-30-2010)
//			* Made ObjectSet properties of database context as virtual and return type as IObjectSet
//			* Made stored procedure (function import) methods virtual and return type as List<Entity>
//			* Seperate name space for data containers	
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Objects.DataClasses;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections.Generic;//custom-code
using YPortal.Helpers;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model_Namespace", "FK_Blasts_Campaigns", "Campaign", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(YPortal.BusinessEntities.Campaign), "Blast", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(YPortal.BusinessEntities.Blast), true)]//custom-code

#endregion


namespace YPortal.BusinessEntities{//custom-code
#region Entities

/// <summary>
/// No Metadata Documentation available.
/// </summary>
[EdmEntityTypeAttribute(NamespaceName="Model_Namespace", Name="AdminUser")]
[Serializable()]
[DataContractAttribute(IsReference=true)]
public partial class AdminUser : EntityObject
{

	
    #region Factory Method

    /// <summary>
    /// Create a new AdminUser object.
    /// </summary>
    /// <param name="userId">Initial value of the UserId property.</param>
    public static AdminUser CreateAdminUser(global::System.Int32 userId)
    {
        AdminUser adminUser = new AdminUser();
        adminUser.UserId = userId;
        return adminUser;
    }

    #endregion

    #region Primitive Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Int32 UserId
    {
        get
        {
            return _UserId;
        }
        set
        {
            if (_UserId != value)
            {
                //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
    			if (value.IsInvalidKey()) BusinessLayerHelper.ThrowErrorForInvalidDataKey("UserId");
    
    
    			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
    			
    			OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
    }
    private global::System.Int32 _UserId;
    partial void OnUserIdChanging(global::System.Int32 value);
    partial void OnUserIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String UserName
    {
        get
        {
            return _UserName;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("UserName");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnUserNameChanging(value);
            ReportPropertyChanging("UserName");
            _UserName = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("UserName");
            OnUserNameChanged();
        }
    }
    private global::System.String _UserName;
    partial void OnUserNameChanging(global::System.String value);
    partial void OnUserNameChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String Password
    {
        get
        {
            return _Password;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("Password");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnPasswordChanging(value);
            ReportPropertyChanging("Password");
            _Password = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("Password");
            OnPasswordChanged();
        }
    }
    private global::System.String _Password;
    partial void OnPasswordChanging(global::System.String value);
    partial void OnPasswordChanged();

    #endregion


}

/// <summary>
/// No Metadata Documentation available.
/// </summary>
[EdmEntityTypeAttribute(NamespaceName="Model_Namespace", Name="AppSetting")]
[Serializable()]
[DataContractAttribute(IsReference=true)]
public partial class AppSetting : EntityObject
{

	
    #region Factory Method

    /// <summary>
    /// Create a new AppSetting object.
    /// </summary>
    /// <param name="appSettingsId">Initial value of the AppSettingsId property.</param>
    public static AppSetting CreateAppSetting(global::System.Int32 appSettingsId)
    {
        AppSetting appSetting = new AppSetting();
        appSetting.AppSettingsId = appSettingsId;
        return appSetting;
    }

    #endregion

    #region Primitive Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Int32 AppSettingsId
    {
        get
        {
            return _AppSettingsId;
        }
        set
        {
            if (_AppSettingsId != value)
            {
                //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
    			if (value.IsInvalidKey()) BusinessLayerHelper.ThrowErrorForInvalidDataKey("AppSettingsId");
    
    
    			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
    			
    			OnAppSettingsIdChanging(value);
                ReportPropertyChanging("AppSettingsId");
                _AppSettingsId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AppSettingsId");
                OnAppSettingsIdChanged();
            }
        }
    }
    private global::System.Int32 _AppSettingsId;
    partial void OnAppSettingsIdChanging(global::System.Int32 value);
    partial void OnAppSettingsIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String AppKey
    {
        get
        {
            return _AppKey;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("AppKey");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnAppKeyChanging(value);
            ReportPropertyChanging("AppKey");
            _AppKey = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("AppKey");
            OnAppKeyChanged();
        }
    }
    private global::System.String _AppKey;
    partial void OnAppKeyChanging(global::System.String value);
    partial void OnAppKeyChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String AppValue
    {
        get
        {
            return _AppValue;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("AppValue");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnAppValueChanging(value);
            ReportPropertyChanging("AppValue");
            _AppValue = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("AppValue");
            OnAppValueChanged();
        }
    }
    private global::System.String _AppValue;
    partial void OnAppValueChanging(global::System.String value);
    partial void OnAppValueChanged();

    #endregion


}

/// <summary>
/// No Metadata Documentation available.
/// </summary>
[EdmEntityTypeAttribute(NamespaceName="Model_Namespace", Name="Blast")]
[Serializable()]
[DataContractAttribute(IsReference=true)]
public partial class Blast : EntityObject
{

	
    #region Factory Method

    /// <summary>
    /// Create a new Blast object.
    /// </summary>
    /// <param name="blastId">Initial value of the BlastId property.</param>
    public static Blast CreateBlast(global::System.Int64 blastId)
    {
        Blast blast = new Blast();
        blast.BlastId = blastId;
        return blast;
    }

    #endregion

    #region Primitive Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Int64 BlastId
    {
        get
        {
            return _BlastId;
        }
        set
        {
            if (_BlastId != value)
            {
                //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
    			
    			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
    			
    			OnBlastIdChanging(value);
                ReportPropertyChanging("BlastId");
                _BlastId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BlastId");
                OnBlastIdChanged();
            }
        }
    }
    private global::System.Int64 _BlastId;
    partial void OnBlastIdChanging(global::System.Int64 value);
    partial void OnBlastIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.Int64> CampaignId
    {
        get
        {
            return _CampaignId;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnCampaignIdChanging(value);
            ReportPropertyChanging("CampaignId");
            _CampaignId = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("CampaignId");
            OnCampaignIdChanged();
        }
    }
    private Nullable<global::System.Int64> _CampaignId;
    partial void OnCampaignIdChanging(Nullable<global::System.Int64> value);
    partial void OnCampaignIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String BlastDisplayName
    {
        get
        {
            return _BlastDisplayName;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("BlastDisplayName");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnBlastDisplayNameChanging(value);
            ReportPropertyChanging("BlastDisplayName");
            _BlastDisplayName = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("BlastDisplayName");
            OnBlastDisplayNameChanged();
        }
    }
    private global::System.String _BlastDisplayName;
    partial void OnBlastDisplayNameChanging(global::System.String value);
    partial void OnBlastDisplayNameChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.DateTime> BlastStartDate
    {
        get
        {
            return _BlastStartDate;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("BlastStartDate");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnBlastStartDateChanging(value);
            ReportPropertyChanging("BlastStartDate");
            _BlastStartDate = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("BlastStartDate");
            OnBlastStartDateChanged();
        }
    }
    private Nullable<global::System.DateTime> _BlastStartDate;
    partial void OnBlastStartDateChanging(Nullable<global::System.DateTime> value);
    partial void OnBlastStartDateChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.DateTime> BlastEndDate
    {
        get
        {
            return _BlastEndDate;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("BlastEndDate");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnBlastEndDateChanging(value);
            ReportPropertyChanging("BlastEndDate");
            _BlastEndDate = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("BlastEndDate");
            OnBlastEndDateChanged();
        }
    }
    private Nullable<global::System.DateTime> _BlastEndDate;
    partial void OnBlastEndDateChanging(Nullable<global::System.DateTime> value);
    partial void OnBlastEndDateChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String BlastType
    {
        get
        {
            return _BlastType;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("BlastType");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnBlastTypeChanging(value);
            ReportPropertyChanging("BlastType");
            _BlastType = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("BlastType");
            OnBlastTypeChanged();
        }
    }
    private global::System.String _BlastType;
    partial void OnBlastTypeChanging(global::System.String value);
    partial void OnBlastTypeChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String BlastStatus
    {
        get
        {
            return _BlastStatus;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("BlastStatus");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnBlastStatusChanging(value);
            ReportPropertyChanging("BlastStatus");
            _BlastStatus = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("BlastStatus");
            OnBlastStatusChanged();
        }
    }
    private global::System.String _BlastStatus;
    partial void OnBlastStatusChanging(global::System.String value);
    partial void OnBlastStatusChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.DateTime> CreatedOn
    {
        get
        {
            return _CreatedOn;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("CreatedOn");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnCreatedOnChanging(value);
            ReportPropertyChanging("CreatedOn");
            _CreatedOn = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("CreatedOn");
            OnCreatedOnChanged();
        }
    }
    private Nullable<global::System.DateTime> _CreatedOn;
    partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
    partial void OnCreatedOnChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.DateTime> ModifiedOn
    {
        get
        {
            return _ModifiedOn;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("ModifiedOn");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnModifiedOnChanging(value);
            ReportPropertyChanging("ModifiedOn");
            _ModifiedOn = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("ModifiedOn");
            OnModifiedOnChanged();
        }
    }
    private Nullable<global::System.DateTime> _ModifiedOn;
    partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
    partial void OnModifiedOnChanged();

    #endregion


    #region Navigation Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [XmlIgnoreAttribute()]
    [SoapIgnoreAttribute()]
    [DataMemberAttribute()]
    [EdmRelationshipNavigationPropertyAttribute("Model_Namespace", "FK_Blasts_Campaigns", "Campaign")]
    public Campaign Campaign
    {
        get
        {
            return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Campaign>("Model_Namespace.FK_Blasts_Campaigns", "Campaign").Value;
        }
        set
        {
            ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Campaign>("Model_Namespace.FK_Blasts_Campaigns", "Campaign").Value = value;
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [BrowsableAttribute(false)]
    [DataMemberAttribute()]
    public EntityReference<Campaign> CampaignReference
    {
        get
        {
            return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Campaign>("Model_Namespace.FK_Blasts_Campaigns", "Campaign");
        }
        set
        {
            if ((value != null))
            {
                ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Campaign>("Model_Namespace.FK_Blasts_Campaigns", "Campaign", value);
            }
        }
    }

    #endregion

}

/// <summary>
/// No Metadata Documentation available.
/// </summary>
[EdmEntityTypeAttribute(NamespaceName="Model_Namespace", Name="Campaign")]
[Serializable()]
[DataContractAttribute(IsReference=true)]
public partial class Campaign : EntityObject
{

	
    #region Factory Method

    /// <summary>
    /// Create a new Campaign object.
    /// </summary>
    /// <param name="campaignId">Initial value of the CampaignId property.</param>
    public static Campaign CreateCampaign(global::System.Int64 campaignId)
    {
        Campaign campaign = new Campaign();
        campaign.CampaignId = campaignId;
        return campaign;
    }

    #endregion

    #region Primitive Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Int64 CampaignId
    {
        get
        {
            return _CampaignId;
        }
        set
        {
            if (_CampaignId != value)
            {
                //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
    			
    			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
    			
    			OnCampaignIdChanging(value);
                ReportPropertyChanging("CampaignId");
                _CampaignId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CampaignId");
                OnCampaignIdChanged();
            }
        }
    }
    private global::System.Int64 _CampaignId;
    partial void OnCampaignIdChanging(global::System.Int64 value);
    partial void OnCampaignIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String CampaignName
    {
        get
        {
            return _CampaignName;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("CampaignName");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnCampaignNameChanging(value);
            ReportPropertyChanging("CampaignName");
            _CampaignName = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("CampaignName");
            OnCampaignNameChanged();
        }
    }
    private global::System.String _CampaignName;
    partial void OnCampaignNameChanging(global::System.String value);
    partial void OnCampaignNameChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String CampaignCode
    {
        get
        {
            return _CampaignCode;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("CampaignCode");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnCampaignCodeChanging(value);
            ReportPropertyChanging("CampaignCode");
            _CampaignCode = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("CampaignCode");
            OnCampaignCodeChanged();
        }
    }
    private global::System.String _CampaignCode;
    partial void OnCampaignCodeChanging(global::System.String value);
    partial void OnCampaignCodeChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.Int64> SilverpopDatabaseId
    {
        get
        {
            return _SilverpopDatabaseId;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnSilverpopDatabaseIdChanging(value);
            ReportPropertyChanging("SilverpopDatabaseId");
            _SilverpopDatabaseId = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("SilverpopDatabaseId");
            OnSilverpopDatabaseIdChanged();
        }
    }
    private Nullable<global::System.Int64> _SilverpopDatabaseId;
    partial void OnSilverpopDatabaseIdChanging(Nullable<global::System.Int64> value);
    partial void OnSilverpopDatabaseIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String SilverpopDatabaseName
    {
        get
        {
            return _SilverpopDatabaseName;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("SilverpopDatabaseName");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnSilverpopDatabaseNameChanging(value);
            ReportPropertyChanging("SilverpopDatabaseName");
            _SilverpopDatabaseName = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("SilverpopDatabaseName");
            OnSilverpopDatabaseNameChanged();
        }
    }
    private global::System.String _SilverpopDatabaseName;
    partial void OnSilverpopDatabaseNameChanging(global::System.String value);
    partial void OnSilverpopDatabaseNameChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.Int32> TotalProspects
    {
        get
        {
            return _TotalProspects;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("TotalProspects");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnTotalProspectsChanging(value);
            ReportPropertyChanging("TotalProspects");
            _TotalProspects = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("TotalProspects");
            OnTotalProspectsChanged();
        }
    }
    private Nullable<global::System.Int32> _TotalProspects;
    partial void OnTotalProspectsChanging(Nullable<global::System.Int32> value);
    partial void OnTotalProspectsChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.Boolean> IsActive
    {
        get
        {
            return _IsActive;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnIsActiveChanging(value);
            ReportPropertyChanging("IsActive");
            _IsActive = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("IsActive");
            OnIsActiveChanged();
        }
    }
    private Nullable<global::System.Boolean> _IsActive;
    partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
    partial void OnIsActiveChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.DateTime> CreatedOn
    {
        get
        {
            return _CreatedOn;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("CreatedOn");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnCreatedOnChanging(value);
            ReportPropertyChanging("CreatedOn");
            _CreatedOn = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("CreatedOn");
            OnCreatedOnChanged();
        }
    }
    private Nullable<global::System.DateTime> _CreatedOn;
    partial void OnCreatedOnChanging(Nullable<global::System.DateTime> value);
    partial void OnCreatedOnChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.DateTime> ModifiedOn
    {
        get
        {
            return _ModifiedOn;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("ModifiedOn");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnModifiedOnChanging(value);
            ReportPropertyChanging("ModifiedOn");
            _ModifiedOn = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("ModifiedOn");
            OnModifiedOnChanged();
        }
    }
    private Nullable<global::System.DateTime> _ModifiedOn;
    partial void OnModifiedOnChanging(Nullable<global::System.DateTime> value);
    partial void OnModifiedOnChanged();

    #endregion


    #region Navigation Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [XmlIgnoreAttribute()]
    [SoapIgnoreAttribute()]
    [DataMemberAttribute()]
    [EdmRelationshipNavigationPropertyAttribute("Model_Namespace", "FK_Blasts_Campaigns", "Blast")]
    public EntityCollection<Blast> Blasts
    {
        get
        {
            return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Blast>("Model_Namespace.FK_Blasts_Campaigns", "Blast");
        }
        set
        {
            if ((value != null))
            {
                ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Blast>("Model_Namespace.FK_Blasts_Campaigns", "Blast", value);
            }
        }
    }

    #endregion

}

/// <summary>
/// No Metadata Documentation available.
/// </summary>
[EdmEntityTypeAttribute(NamespaceName="Model_Namespace", Name="Contact")]
[Serializable()]
[DataContractAttribute(IsReference=true)]
public partial class Contact : EntityObject
{

	
    #region Factory Method

    /// <summary>
    /// Create a new Contact object.
    /// </summary>
    /// <param name="contactId">Initial value of the ContactId property.</param>
    public static Contact CreateContact(global::System.Int32 contactId)
    {
        Contact contact = new Contact();
        contact.ContactId = contactId;
        return contact;
    }

    #endregion

    #region Primitive Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Int32 ContactId
    {
        get
        {
            return _ContactId;
        }
        set
        {
            if (_ContactId != value)
            {
                //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
    			if (value.IsInvalidKey()) BusinessLayerHelper.ThrowErrorForInvalidDataKey("ContactId");
    
    
    			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
    			
    			OnContactIdChanging(value);
                ReportPropertyChanging("ContactId");
                _ContactId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ContactId");
                OnContactIdChanged();
            }
        }
    }
    private global::System.Int32 _ContactId;
    partial void OnContactIdChanging(global::System.Int32 value);
    partial void OnContactIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String FirstName
    {
        get
        {
            return _FirstName;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("FirstName");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnFirstNameChanging(value);
            ReportPropertyChanging("FirstName");
            _FirstName = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("FirstName");
            OnFirstNameChanged();
        }
    }
    private global::System.String _FirstName;
    partial void OnFirstNameChanging(global::System.String value);
    partial void OnFirstNameChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String LastName
    {
        get
        {
            return _LastName;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("LastName");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnLastNameChanging(value);
            ReportPropertyChanging("LastName");
            _LastName = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("LastName");
            OnLastNameChanged();
        }
    }
    private global::System.String _LastName;
    partial void OnLastNameChanging(global::System.String value);
    partial void OnLastNameChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String Email
    {
        get
        {
            return _Email;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("Email");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnEmailChanging(value);
            ReportPropertyChanging("Email");
            _Email = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("Email");
            OnEmailChanged();
        }
    }
    private global::System.String _Email;
    partial void OnEmailChanging(global::System.String value);
    partial void OnEmailChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String Phone
    {
        get
        {
            return _Phone;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("Phone");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnPhoneChanging(value);
            ReportPropertyChanging("Phone");
            _Phone = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("Phone");
            OnPhoneChanged();
        }
    }
    private global::System.String _Phone;
    partial void OnPhoneChanging(global::System.String value);
    partial void OnPhoneChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String Location
    {
        get
        {
            return _Location;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("Location");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnLocationChanging(value);
            ReportPropertyChanging("Location");
            _Location = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("Location");
            OnLocationChanged();
        }
    }
    private global::System.String _Location;
    partial void OnLocationChanging(global::System.String value);
    partial void OnLocationChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String Interests
    {
        get
        {
            return _Interests;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("Interests");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnInterestsChanging(value);
            ReportPropertyChanging("Interests");
            _Interests = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("Interests");
            OnInterestsChanged();
        }
    }
    private global::System.String _Interests;
    partial void OnInterestsChanging(global::System.String value);
    partial void OnInterestsChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String Feedback
    {
        get
        {
            return _Feedback;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("Feedback");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnFeedbackChanging(value);
            ReportPropertyChanging("Feedback");
            _Feedback = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("Feedback");
            OnFeedbackChanged();
        }
    }
    private global::System.String _Feedback;
    partial void OnFeedbackChanging(global::System.String value);
    partial void OnFeedbackChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.DateTime> DateSubmitted
    {
        get
        {
            return _DateSubmitted;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("DateSubmitted");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnDateSubmittedChanging(value);
            ReportPropertyChanging("DateSubmitted");
            _DateSubmitted = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("DateSubmitted");
            OnDateSubmittedChanged();
        }
    }
    private Nullable<global::System.DateTime> _DateSubmitted;
    partial void OnDateSubmittedChanging(Nullable<global::System.DateTime> value);
    partial void OnDateSubmittedChanged();

    #endregion


}

/// <summary>
/// No Metadata Documentation available.
/// </summary>
[EdmEntityTypeAttribute(NamespaceName="Model_Namespace", Name="Interest")]
[Serializable()]
[DataContractAttribute(IsReference=true)]
public partial class Interest : EntityObject
{

	
    #region Factory Method

    /// <summary>
    /// Create a new Interest object.
    /// </summary>
    /// <param name="interestId">Initial value of the InterestId property.</param>
    public static Interest CreateInterest(global::System.Int32 interestId)
    {
        Interest interest = new Interest();
        interest.InterestId = interestId;
        return interest;
    }

    #endregion

    #region Primitive Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Int32 InterestId
    {
        get
        {
            return _InterestId;
        }
        set
        {
            if (_InterestId != value)
            {
                //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
    			if (value.IsInvalidKey()) BusinessLayerHelper.ThrowErrorForInvalidDataKey("InterestId");
    
    
    			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
    			
    			OnInterestIdChanging(value);
                ReportPropertyChanging("InterestId");
                _InterestId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InterestId");
                OnInterestIdChanged();
            }
        }
    }
    private global::System.Int32 _InterestId;
    partial void OnInterestIdChanging(global::System.Int32 value);
    partial void OnInterestIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String Name
    {
        get
        {
            return _Name;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("Name");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnNameChanging(value);
            ReportPropertyChanging("Name");
            _Name = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("Name");
            OnNameChanged();
        }
    }
    private global::System.String _Name;
    partial void OnNameChanging(global::System.String value);
    partial void OnNameChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.Int32> DisplayOrder
    {
        get
        {
            return _DisplayOrder;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("DisplayOrder");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnDisplayOrderChanging(value);
            ReportPropertyChanging("DisplayOrder");
            _DisplayOrder = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("DisplayOrder");
            OnDisplayOrderChanged();
        }
    }
    private Nullable<global::System.Int32> _DisplayOrder;
    partial void OnDisplayOrderChanging(Nullable<global::System.Int32> value);
    partial void OnDisplayOrderChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String GroupName
    {
        get
        {
            return _GroupName;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("GroupName");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnGroupNameChanging(value);
            ReportPropertyChanging("GroupName");
            _GroupName = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("GroupName");
            OnGroupNameChanged();
        }
    }
    private global::System.String _GroupName;
    partial void OnGroupNameChanging(global::System.String value);
    partial void OnGroupNameChanged();

    #endregion


}

/// <summary>
/// No Metadata Documentation available.
/// </summary>
[EdmEntityTypeAttribute(NamespaceName="Model_Namespace", Name="LandingPageProspect")]
[Serializable()]
[DataContractAttribute(IsReference=true)]
public partial class LandingPageProspect : EntityObject
{

	
    #region Factory Method

    /// <summary>
    /// Create a new LandingPageProspect object.
    /// </summary>
    /// <param name="prospectId">Initial value of the ProspectId property.</param>
    public static LandingPageProspect CreateLandingPageProspect(global::System.Int32 prospectId)
    {
        LandingPageProspect landingPageProspect = new LandingPageProspect();
        landingPageProspect.ProspectId = prospectId;
        return landingPageProspect;
    }

    #endregion

    #region Primitive Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Int32 ProspectId
    {
        get
        {
            return _ProspectId;
        }
        set
        {
            if (_ProspectId != value)
            {
                //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
    			if (value.IsInvalidKey()) BusinessLayerHelper.ThrowErrorForInvalidDataKey("ProspectId");
    
    
    			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
    			
    			OnProspectIdChanging(value);
                ReportPropertyChanging("ProspectId");
                _ProspectId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProspectId");
                OnProspectIdChanged();
            }
        }
    }
    private global::System.Int32 _ProspectId;
    partial void OnProspectIdChanging(global::System.Int32 value);
    partial void OnProspectIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.DateTime> SubmittedOn
    {
        get
        {
            return _SubmittedOn;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("SubmittedOn");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnSubmittedOnChanging(value);
            ReportPropertyChanging("SubmittedOn");
            _SubmittedOn = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("SubmittedOn");
            OnSubmittedOnChanged();
        }
    }
    private Nullable<global::System.DateTime> _SubmittedOn;
    partial void OnSubmittedOnChanging(Nullable<global::System.DateTime> value);
    partial void OnSubmittedOnChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String FirstName
    {
        get
        {
            return _FirstName;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("FirstName");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnFirstNameChanging(value);
            ReportPropertyChanging("FirstName");
            _FirstName = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("FirstName");
            OnFirstNameChanged();
        }
    }
    private global::System.String _FirstName;
    partial void OnFirstNameChanging(global::System.String value);
    partial void OnFirstNameChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String LastName
    {
        get
        {
            return _LastName;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("LastName");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnLastNameChanging(value);
            ReportPropertyChanging("LastName");
            _LastName = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("LastName");
            OnLastNameChanged();
        }
    }
    private global::System.String _LastName;
    partial void OnLastNameChanging(global::System.String value);
    partial void OnLastNameChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String Email
    {
        get
        {
            return _Email;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("Email");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnEmailChanging(value);
            ReportPropertyChanging("Email");
            _Email = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("Email");
            OnEmailChanged();
        }
    }
    private global::System.String _Email;
    partial void OnEmailChanging(global::System.String value);
    partial void OnEmailChanged();

    #endregion


}

/// <summary>
/// No Metadata Documentation available.
/// </summary>
[EdmEntityTypeAttribute(NamespaceName="Model_Namespace", Name="Location")]
[Serializable()]
[DataContractAttribute(IsReference=true)]
public partial class Location : EntityObject
{

	
    #region Factory Method

    /// <summary>
    /// Create a new Location object.
    /// </summary>
    /// <param name="locationId">Initial value of the LocationId property.</param>
    public static Location CreateLocation(global::System.Int32 locationId)
    {
        Location location = new Location();
        location.LocationId = locationId;
        return location;
    }

    #endregion

    #region Primitive Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Int32 LocationId
    {
        get
        {
            return _LocationId;
        }
        set
        {
            if (_LocationId != value)
            {
                //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
    			if (value.IsInvalidKey()) BusinessLayerHelper.ThrowErrorForInvalidDataKey("LocationId");
    
    
    			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
    			
    			OnLocationIdChanging(value);
                ReportPropertyChanging("LocationId");
                _LocationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationId");
                OnLocationIdChanged();
            }
        }
    }
    private global::System.Int32 _LocationId;
    partial void OnLocationIdChanging(global::System.Int32 value);
    partial void OnLocationIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String Name
    {
        get
        {
            return _Name;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("Name");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnNameChanging(value);
            ReportPropertyChanging("Name");
            _Name = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("Name");
            OnNameChanged();
        }
    }
    private global::System.String _Name;
    partial void OnNameChanging(global::System.String value);
    partial void OnNameChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.Int32> DisplayOrder
    {
        get
        {
            return _DisplayOrder;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("DisplayOrder");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnDisplayOrderChanging(value);
            ReportPropertyChanging("DisplayOrder");
            _DisplayOrder = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("DisplayOrder");
            OnDisplayOrderChanged();
        }
    }
    private Nullable<global::System.Int32> _DisplayOrder;
    partial void OnDisplayOrderChanging(Nullable<global::System.Int32> value);
    partial void OnDisplayOrderChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String Email
    {
        get
        {
            return _Email;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("Email");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnEmailChanging(value);
            ReportPropertyChanging("Email");
            _Email = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("Email");
            OnEmailChanged();
        }
    }
    private global::System.String _Email;
    partial void OnEmailChanging(global::System.String value);
    partial void OnEmailChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String EmailTemplate
    {
        get
        {
            return _EmailTemplate;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("EmailTemplate");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnEmailTemplateChanging(value);
            ReportPropertyChanging("EmailTemplate");
            _EmailTemplate = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("EmailTemplate");
            OnEmailTemplateChanged();
        }
    }
    private global::System.String _EmailTemplate;
    partial void OnEmailTemplateChanging(global::System.String value);
    partial void OnEmailTemplateChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String LocationPage
    {
        get
        {
            return _LocationPage;
        }
        set
        {
            //-- Logic for Null and Empty Value Validation [CUSTOM CODE]
			
			if (value.IsEmpty()) BusinessLayerHelper.ThrowErrorForEmptyValue("LocationPage");


			//-- Logic for Null and Empty Value Validation Ends [CUSTOM CODE]
			
			OnLocationPageChanging(value);
            ReportPropertyChanging("LocationPage");
            _LocationPage = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("LocationPage");
            OnLocationPageChanged();
        }
    }
    private global::System.String _LocationPage;
    partial void OnLocationPageChanging(global::System.String value);
    partial void OnLocationPageChanged();

    #endregion


}

#endregion



}
