//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPortal.Web.User_Control {
    
    
    public partial class YDSiteMapControlV2 {
        
        /// <summary>
        /// ProgsCampsMnu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC ProgsCampsMnu1;
        
        /// <summary>
        /// ProgPreschoolMnu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC ProgPreschoolMnu1;
        
        /// <summary>
        /// ProgSwimMnu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC ProgSwimMnu1;
        
        /// <summary>
        /// ProgSportsMnu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC ProgSportsMnu1;
        
        /// <summary>
        /// ProgBaseMnu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC ProgBaseMnu1;
        
        /// <summary>
        /// ProgComProgMnu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC ProgComProgMnu1;
        
        /// <summary>
        /// ProgPersonalTrainingMnu1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC ProgPersonalTrainingMnu1;
        
        /// <summary>
        /// YMenuLocationFamCenters1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC YMenuLocationFamCenters1;
        
        /// <summary>
        /// YMenuLocationPreschool1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC YMenuLocationPreschool1;
        
        /// <summary>
        /// YMenuLocationHeadStart1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC YMenuLocationHeadStart1;
        
        /// <summary>
        /// YMenuLocationBASE1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC YMenuLocationBASE1;
        
        /// <summary>
        /// YMenuLocationsAO1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC YMenuLocationsAO1;
        
        /// <summary>
        /// YMenuLocationsCamps1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC YMenuLocationsCamps1;
        
        /// <summary>
        /// YMembershipSection1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC YMembershipSection1;
        
        /// <summary>
        /// YMembershipSection2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC YMembershipSection2;
        
        /// <summary>
        /// YMenuSectionOurMission1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC YMenuSectionOurMission1;
        
        /// <summary>
        /// YMenuSectionOurMission2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDMenuSectionUC YMenuSectionOurMission2;
    }
}
