//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPortal.Web.footer {
    
    
    public partial class volunteer_content {
        
        /// <summary>
        /// YDCarouselInfoV21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.User_Control.YDCarouselInfoV2 YDCarouselInfoV21;
        
        /// <summary>
        /// YDTabControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.Controls.YDTabControl YDTabControl1;
        
        /// <summary>
        /// YDTabControl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.Controls.YDTabControl YDTabControl2;
        
        /// <summary>
        /// YDTabControl3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.Controls.YDTabControl YDTabControl3;
        
        /// <summary>
        /// YDTabControl4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::YPortal.Web.Controls.YDTabControl YDTabControl4;
    }
}
