//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YPortal.Web.locations.before_and_after_school_programs
{


    public partial class before_and_after_school_programs
    {
    }
}
